/**
 * B4X Layout ↔ JSON conversion module.
 *
 * Key transformations:
 *  - Map<string, PropertyValue>  ↔  plain object Record<string, JsonPropertyValue>
 *  - TypeTag numeric enum        ↔  human-readable string name ("Int32", "Color", …)
 *  - ColorValue {a,r,g,b}        ↔  "#AARRGGBB" hex string
 *  - TypeTag.StringRef preserved ↔  "StringRef" tag (round-trip fidelity;
 *    agents may freely use "String" for any value they create/modify)
 *  - ScriptData.rawCompressedBytes  omitted (regenerated by writeLayoutFile)
 */

import {
    LayoutFile, ControlNode, PropertyValue, TypeTag,
    Variant, ManifestEntry, ScriptData, VariantScript,
} from '../models/types';

// ── JSON property-value shape ────────────────────────────────────────

export type JsonPropertyValue =
    | { tag: 'Int32';      value: number }
    | { tag: 'String';     value: string }
    | { tag: 'StringRef';  value: string }
    | { tag: 'Float';      value: number }
    | { tag: 'Double';     value: number }
    | { tag: 'Bool';       value: boolean }
    | { tag: 'Color';      value: string  }  // "#AARRGGBB" hex
    | { tag: 'Int32Rect';  x: number; y: number; width: number; height: number }
    | { tag: 'Null' }
    | { tag: 'Object';     value: Record<string, JsonPropertyValue> }
    | { tag: 'ErRef';      value: number };

// ── Control node ─────────────────────────────────────────────────────

export interface JsonControlNode {
    /** All properties stored on this control (key → typed value). */
    properties: Record<string, JsonPropertyValue>;
    /** Child controls nested under this control. */
    children:   JsonControlNode[];
}

// ── Top-level layout file ────────────────────────────────────────────

export interface JsonLayoutFile {
    /**
     * Layout file format version. Currently always 5.
     * Do not change this value.
     */
    version: number;

    /**
     * Grid snap size in dp/points (default 10).
     */
    gridSize: number;

    /**
     * Screen variants (responsive breakpoints).
     * Each control stores its position/size per variant index.
     * variant 0 is the default (design-time) variant.
     */
    variants: Array<{ scale: number; width: number; height: number }>;

    /**
     * Control manifest — one entry per control in the layout,
     * listing the control name and its platform type identifiers.
     * Updated automatically by the B4X designer when controls are added/removed.
     */
    manifest: Array<{ name: string; javaType: string; csType: string }>;

    /**
     * Project file references (image/font filenames used by this layout).
     */
    fileReferences: string[];

    /**
     * Designer script data. null when no scripts have been written.
     * mainScript runs for all variants; each variantScript runs after mainScript
     * when the designer switches to that variant.
     */
    scriptData: {
        mainScript: string;
        variantScripts: Array<{
            variant: { scale: number; width: number; height: number };
            script: string;
        }>;
    } | null;

    /**
     * Trailing serialization flags.
     * Safe to leave as { c: false, d: false } unless you know what you are doing.
     */
    flags: { c: boolean; d: boolean };

    /**
     * Root control node containing the entire control tree.
     * The root is always a MetaMain (Activity / Main) control.
     * Its children are the top-level controls on the layout canvas.
     */
    rootControl: JsonControlNode;
}

// ── Serialization helpers ──────────────────────────────────────────

function byteToHex(n: number): string {
    return n.toString(16).padStart(2, '0').toUpperCase();
}

function colorToHex(a: number, r: number, g: number, b: number): string {
    return `#${byteToHex(a)}${byteToHex(r)}${byteToHex(g)}${byteToHex(b)}`;
}

function serializePropertyValue(pv: PropertyValue): JsonPropertyValue {
    switch (pv.tag) {
        case TypeTag.Int32:     return { tag: 'Int32',    value: pv.value };
        case TypeTag.String:    return { tag: 'String',   value: pv.value };
        case TypeTag.StringRef: return { tag: 'StringRef', value: pv.value };
        case TypeTag.Float:     return { tag: 'Float',    value: pv.value };
        case TypeTag.Double:    return { tag: 'Double',   value: pv.value };
        case TypeTag.Bool:      return { tag: 'Bool',     value: pv.value };
        case TypeTag.ErRef:     return { tag: 'ErRef',    value: pv.value };
        case TypeTag.Null:      return { tag: 'Null' };

        case TypeTag.Color:
            return { tag: 'Color', value: colorToHex(pv.a, pv.r, pv.g, pv.b) };

        case TypeTag.Int32Rect:
            return { tag: 'Int32Rect', x: pv.x, y: pv.y, width: pv.width, height: pv.height };

        case TypeTag.Object: {
            const nested: Record<string, JsonPropertyValue> = {};
            for (const [k, v] of pv.value) {
                nested[k] = serializePropertyValue(v);
            }
            return { tag: 'Object', value: nested };
        }
    }
}

function serializeControlNode(node: ControlNode): JsonControlNode {
    const properties: Record<string, JsonPropertyValue> = {};
    for (const [key, value] of node.properties) {
        properties[key] = serializePropertyValue(value);
    }
    return {
        properties,
        children: node.children.map(serializeControlNode),
    };
}

// ── Deserialization helpers ────────────────────────────────────────

function hexToBytes(hex: string, field: string): { a: number; r: number; g: number; b: number } {
    const clean = hex.startsWith('#') ? hex.slice(1) : hex;
    if (!/^[0-9a-fA-F]{8}$/.test(clean)) {
        throw new Error(
            `Invalid color value for "${field}": "${hex}". ` +
            'Expected "#AARRGGBB" — 8 hex digits with optional leading "#".',
        );
    }
    return {
        a: parseInt(clean.slice(0, 2), 16),
        r: parseInt(clean.slice(2, 4), 16),
        g: parseInt(clean.slice(4, 6), 16),
        b: parseInt(clean.slice(6, 8), 16),
    };
}

function deserializePropertyValue(jv: JsonPropertyValue, keyPath: string): PropertyValue {
    switch (jv.tag) {
        case 'Int32':     return { tag: TypeTag.Int32,     value: jv.value };
        case 'String':    return { tag: TypeTag.String,    value: jv.value };
        case 'StringRef': return { tag: TypeTag.StringRef, value: jv.value };
        case 'Float':     return { tag: TypeTag.Float,     value: jv.value };
        case 'Double':    return { tag: TypeTag.Double,    value: jv.value };
        case 'Bool':      return { tag: TypeTag.Bool,      value: jv.value };
        case 'ErRef':     return { tag: TypeTag.ErRef,     value: jv.value };
        case 'Null':      return { tag: TypeTag.Null };

        case 'Color': {
            const { a, r, g, b } = hexToBytes(jv.value, keyPath);
            return { tag: TypeTag.Color, a, r, g, b };
        }

        case 'Int32Rect':
            return {
                tag:    TypeTag.Int32Rect,
                x:      jv.x,
                y:      jv.y,
                width:  jv.width,
                height: jv.height,
            };

        case 'Object': {
            const nested = new Map<string, PropertyValue>();
            for (const [k, v] of Object.entries(jv.value)) {
                nested.set(k, deserializePropertyValue(v, `${keyPath}.${k}`));
            }
            return { tag: TypeTag.Object, value: nested };
        }
    }
}

function deserializeControlNode(jn: JsonControlNode, path: string): ControlNode {
    const properties = new Map<string, PropertyValue>();
    for (const [key, value] of Object.entries(jn.properties)) {
        properties.set(key, deserializePropertyValue(value, `${path}.${key}`));
    }
    return {
        properties,
        children: jn.children.map((child, i) =>
            deserializeControlNode(child, `${path}.children[${i}]`),
        ),
    };
}

// ── Deserialization validation helpers ─────────────────────────────

function assertNumber(value: unknown, field: string): number {
    if (typeof value !== 'number') {
        throw new Error(`Expected number for field "${field}", got ${typeof value}.`);
    }
    return value;
}

function assertArray(value: unknown, field: string): unknown[] {
    if (!Array.isArray(value)) {
        throw new Error(`Expected array for field "${field}", got ${typeof value}.`);
    }
    return value;
}

// ── Public API ─────────────────────────────────────────────────────

/**
 * Serialize a LayoutFile to a JSON-friendly plain object.
 *
 * The returned value is safe to pass directly to JSON.stringify().
 * ScriptData.rawCompressedBytes is intentionally omitted; scripts are
 * stored as plain text and recompressed when writing back to binary.
 *
 * @param layout  Parsed layout model (from parseLayoutFile).
 * @returns       Plain-object representation suitable for JSON.
 */
export function serializeLayoutFile(layout: LayoutFile): JsonLayoutFile {
    return {
        version:    layout.version,
        gridSize:   layout.gridSize,
        variants:   layout.variants.map(v => ({ scale: v.scale, width: v.width, height: v.height })),
        manifest:   layout.manifest.map(m => ({ name: m.name, javaType: m.javaType, csType: m.csType })),
        fileReferences: [...layout.fileReferences],
        scriptData: layout.scriptData
            ? {
                mainScript:     layout.scriptData.mainScript,
                variantScripts: layout.scriptData.variantScripts.map(vs => ({
                    variant: { scale: vs.variant.scale, width: vs.variant.width, height: vs.variant.height },
                    script:  vs.script,
                })),
            }
            : null,
        flags:       { ...layout.flags },
        rootControl: serializeControlNode(layout.rootControl),
    };
}

/**
 * Deserialize a JsonLayoutFile plain object back into a LayoutFile.
 *
 * Throws a descriptive Error if required fields are missing or have the
 * wrong type.  The returned LayoutFile can be passed directly to
 * writeLayoutFile() to produce a binary .bal/.bjl file.
 *
 * @param json  Plain object produced by JSON.parse() (or by serializeLayoutFile()).
 * @returns     Fully restored LayoutFile model.
 */
export function deserializeLayoutFile(json: JsonLayoutFile): LayoutFile {
    assertNumber(json.version,  'version');
    assertNumber(json.gridSize, 'gridSize');
    assertArray(json.variants,       'variants');
    assertArray(json.manifest,       'manifest');
    assertArray(json.fileReferences, 'fileReferences');

    if (!json.rootControl || typeof json.rootControl !== 'object') {
        throw new Error('Missing or invalid field "rootControl": expected an object.');
    }

    // Variants
    const variants: Variant[] = (json.variants as Array<{ scale: number; width: number; height: number }>)
        .map((v, i) => {
            if (
                typeof v.scale  !== 'number' ||
                typeof v.width  !== 'number' ||
                typeof v.height !== 'number'
            ) {
                throw new Error(
                    `Invalid variant at index ${i}: expected { scale: number, width: number, height: number }.`,
                );
            }
            return { scale: v.scale, width: v.width, height: v.height };
        });

    // Manifest
    const manifest: ManifestEntry[] = (json.manifest as Array<{ name: string; javaType: string; csType: string }>)
        .map((m, i) => {
            if (
                typeof m.name     !== 'string' ||
                typeof m.javaType !== 'string' ||
                typeof m.csType   !== 'string'
            ) {
                throw new Error(
                    `Invalid manifest entry at index ${i}: expected { name: string, javaType: string, csType: string }.`,
                );
            }
            return { name: m.name, javaType: m.javaType, csType: m.csType };
        });

    // Script data
    let scriptData: ScriptData | null = null;
    if (json.scriptData !== null && json.scriptData !== undefined) {
        const variantScripts: VariantScript[] = (json.scriptData.variantScripts ?? []).map((vs, i) => {
            if (!vs.variant || typeof vs.script !== 'string') {
                throw new Error(`Invalid variantScript at index ${i}: expected { variant, script }.`);
            }
            return {
                variant: {
                    scale:  vs.variant.scale,
                    width:  vs.variant.width,
                    height: vs.variant.height,
                },
                script: vs.script,
                // rawCompressedBytes intentionally absent — writeLayoutFile will recompress
            };
        });

        scriptData = {
            mainScript:     json.scriptData.mainScript ?? '',
            variantScripts,
            // rawCompressedBytes intentionally absent — writeLayoutFile will recompress
        };
    }

    return {
        version:        json.version,
        gridSize:       json.gridSize,
        variants,
        manifest,
        fileReferences: [...json.fileReferences],
        scriptData,
        flags:          { c: !!json.flags?.c, d: !!json.flags?.d },
        rootControl:    deserializeControlNode(json.rootControl, 'rootControl'),
    };
}
